apiVersion: v1
kind: Pod
metadata: 
  name: testing
  namespace: deploy
  labels:
    name: testing
spec:
  containers:
    - name: testing
      image: bitbull/webserver
      ports:
      - containerPort: 80
      env:
      - name: Myusername
        valueFrom:
          configMapKeyRef:
             name: core
             key: Description
      volumeMounts:
        - name: config-name
          mountPath: "/home/pankhurichauhan21/pvc-file/configmap.yaml/"
          readOnly: true
  
  volumes:
    - name: config-name
      configMap:
        name: core      

