apiVersion: v1
kind: Pod
metadata: 
  name: testing
  namespace: deploy
  labels:
    name: testing
spec:
  containers:
    - name: testing
      image: bitbull/webserver
      ports:
      - containerPort: 80
      env:
      - name: Myusername
        valueFrom:
          secretKeyRef:
             name: my-secret
             key: username

